name: 'DocCov'
description: 'Documentation coverage and drift detection for TypeScript'
author: 'Ryan Waits'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  min-coverage:
    description: 'Minimum coverage percentage (0-100)'
    required: false
    default: '80'
  require-examples:
    description: 'Require @example blocks on all exports'
    required: false
    default: 'false'
  strict:
    description: |
      Fail conditions. Use preset name or comma-separated checks:
      Presets: ci (breaking,regression), release (all), quality (drift,undocumented)
      Custom: "breaking,drift,undocumented"
    required: false
    default: ''
  docs-glob:
    description: 'Glob pattern for markdown docs to check for impact (e.g., "docs/**/*.md")'
    required: false
    default: ''
  format:
    description: 'Output format for diff: text, json, github'
    required: false
    default: 'github'
  comment-on-pr:
    description: 'Post coverage report as PR comment'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for the check'
    required: false
    default: '.'
  skip-spec:
    description: 'Skip spec generation and use existing openpkg.json'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}

outputs:
  coverage:
    description: 'Current coverage percentage'
  coverage-delta:
    description: 'Coverage change compared to base (on PRs)'
  drift-count:
    description: 'Number of drift issues detected'
  docs-impact-count:
    description: 'Number of docs files needing updates'
  
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install DocCov CLI
      shell: bash
      run: npm install -g @doccov/cli

    - name: Generate spec
      if: inputs.skip-spec != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: doccov spec --output openpkg.json

    - name: Verify spec exists
      if: inputs.skip-spec == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ ! -f openpkg.json ]; then
          echo "Error: openpkg.json not found. Either commit it or set skip-spec to false."
          exit 1
        fi

    - name: Check coverage
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ARGS="--min-coverage ${{ inputs.min-coverage }}"
        if [ "${{ inputs.require-examples }}" = "true" ]; then
          ARGS="$ARGS --examples presence"
        fi
        doccov check $ARGS

    - name: Generate base spec (PRs only)
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        git fetch origin ${{ github.base_ref }}
        git checkout FETCH_HEAD -- . 2>/dev/null || true
        if [ "${{ inputs.skip-spec }}" = "true" ] && [ -f openpkg.json ]; then
          cp openpkg.json openpkg-base.json
        else
          doccov spec --output openpkg-base.json 2>/dev/null || echo '{"docs":{"coverageScore":0},"exports":[]}' > openpkg-base.json
        fi
        git checkout - -- . 2>/dev/null || true

    - name: Run diff (PRs only)
      if: github.event_name == 'pull_request'
      id: diff
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f openpkg-base.json ]; then
          # Get JSON output for PR comment
          DIFF_ARGS="--format json"
          if [ -n "${{ inputs.docs-glob }}" ]; then
            DIFF_ARGS="$DIFF_ARGS --docs '${{ inputs.docs-glob }}'"
          fi
          DIFF=$(eval "doccov diff openpkg-base.json openpkg.json $DIFF_ARGS")
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Output GitHub annotations (PRs only)
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f openpkg-base.json ]; then
          DIFF_ARGS="--format github"
          if [ -n "${{ inputs.docs-glob }}" ]; then
            DIFF_ARGS="$DIFF_ARGS --docs '${{ inputs.docs-glob }}'"
          fi
          eval "doccov diff openpkg-base.json openpkg.json $DIFF_ARGS" || true
        fi

    - name: Check strict conditions
      if: github.event_name == 'pull_request' && inputs.strict != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f openpkg-base.json ]; then
          DIFF_ARGS="--format text --strict '${{ inputs.strict }}'"
          if [ -n "${{ inputs.docs-glob }}" ]; then
            DIFF_ARGS="$DIFF_ARGS --docs '${{ inputs.docs-glob }}'"
          fi
          eval "doccov diff openpkg-base.json openpkg.json $DIFF_ARGS"
        fi

    - name: Generate PR comment
      if: github.event_name == 'pull_request' && inputs.comment-on-pr == 'true'
      id: comment
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f openpkg-base.json ]; then
          COMMENT_ARGS="--format pr-comment"
          COMMENT_ARGS="$COMMENT_ARGS --repo-url https://github.com/${{ github.repository }}"
          COMMENT_ARGS="$COMMENT_ARGS --sha ${{ github.event.pull_request.head.sha }}"
          COMMENT_ARGS="$COMMENT_ARGS --min-coverage ${{ inputs.min-coverage }}"
          if [ -n "${{ inputs.docs-glob }}" ]; then
            COMMENT_ARGS="$COMMENT_ARGS --docs '${{ inputs.docs-glob }}'"
          fi

          COMMENT=$(eval "doccov diff openpkg-base.json openpkg.json $COMMENT_ARGS")
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Post PR comment
      if: github.event_name == 'pull_request' && inputs.comment-on-pr == 'true' && steps.comment.outputs.body != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const body = process.env.COMMENT_BODY;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existing = comments.find(c => c.body?.includes('DocCov'));

          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }
      env:
        COMMENT_BODY: ${{ steps.comment.outputs.body }}

