name: 'DocCov'
description: 'Documentation coverage and drift detection for TypeScript'
author: 'Ryan Waits'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  min-coverage:
    description: 'Minimum coverage percentage (0-100)'
    required: false
    default: '80'
  require-examples:
    description: 'Require @example blocks on all exports'
    required: false
    default: 'false'
  fail-on-regression:
    description: 'Fail if coverage regresses compared to base branch'
    required: false
    default: 'false'
  fail-on-drift:
    description: 'Fail if new drift is introduced'
    required: false
    default: 'false'
  docs-glob:
    description: 'Glob pattern for markdown docs to check for impact (e.g., "docs/**/*.md")'
    required: false
    default: ''
  fail-on-docs-impact:
    description: 'Fail if docs need updates due to API changes'
    required: false
    default: 'false'
  comment-on-pr:
    description: 'Post coverage report as PR comment'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for the check'
    required: false
    default: '.'
  skip-generate:
    description: 'Skip spec generation and use existing openpkg.json'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}

outputs:
  coverage:
    description: 'Current coverage percentage'
  coverage-delta:
    description: 'Coverage change compared to base (on PRs)'
  drift-count:
    description: 'Number of drift issues detected'
  docs-impact-count:
    description: 'Number of docs files needing updates'
  
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install DocCov CLI
      shell: bash
      run: npm install -g @doccov/cli

    - name: Generate spec
      if: inputs.skip-generate != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: doccov generate --output openpkg.json

    - name: Verify spec exists
      if: inputs.skip-generate == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ ! -f openpkg.json ]; then
          echo "Error: openpkg.json not found. Either commit it or set skip-generate to false."
          exit 1
        fi

    - name: Check coverage
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ARGS="--min-coverage ${{ inputs.min-coverage }}"
        if [ "${{ inputs.require-examples }}" = "true" ]; then
          ARGS="$ARGS --require-examples"
        fi
        doccov check $ARGS

    - name: Generate base spec (PRs only)
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        git fetch origin ${{ github.base_ref }}
        git checkout FETCH_HEAD -- . 2>/dev/null || true
        if [ "${{ inputs.skip-generate }}" = "true" ] && [ -f openpkg.json ]; then
          cp openpkg.json openpkg-base.json
        else
          doccov generate --output openpkg-base.json 2>/dev/null || echo '{"docs":{"coverageScore":0},"exports":[]}' > openpkg-base.json
        fi
        git checkout - -- . 2>/dev/null || true

    - name: Run diff (PRs only)
      if: github.event_name == 'pull_request'
      id: diff
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f openpkg-base.json ]; then
          DIFF_ARGS="--output json"
          if [ -n "${{ inputs.docs-glob }}" ]; then
            DIFF_ARGS="$DIFF_ARGS --docs '${{ inputs.docs-glob }}'"
          fi
          DIFF=$(eval "doccov diff openpkg-base.json openpkg.json $DIFF_ARGS")
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Check docs impact
      if: github.event_name == 'pull_request' && inputs.fail-on-docs-impact == 'true' && inputs.docs-glob != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f openpkg-base.json ]; then
          doccov diff openpkg-base.json openpkg.json --docs '${{ inputs.docs-glob }}' --fail-on-docs-impact
        fi

    - name: Post PR comment
      if: github.event_name == 'pull_request' && inputs.comment-on-pr == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const diff = JSON.parse(process.env.DIFF_RESULT || '{}');
          
          const emoji = diff.coverageDelta > 0 ? 'ðŸ“ˆ' : diff.coverageDelta < 0 ? 'ðŸ“‰' : 'âž¡ï¸';
          const delta = diff.coverageDelta > 0 ? `+${diff.coverageDelta}` : String(diff.coverageDelta || 0);
          
          let body = `## ${emoji} DocCov Report\n\n`;
          body += `| Metric | Value |\n|--------|-------|\n`;
          body += `| Coverage | ${diff.oldCoverage || 0}% â†’ ${diff.newCoverage || 0}% (${delta}%) |\n`;
          body += `| New exports | ${diff.nonBreaking?.length || 0} |\n`;
          body += `| Undocumented | ${diff.newUndocumented?.length || 0} |\n`;
          body += `| Drift introduced | ${diff.driftIntroduced || 0} |\n`;
          body += `| Drift resolved | ${diff.driftResolved || 0} |\n`;
          
          // Add docs impact section if available
          if (diff.docsImpact) {
            const impact = diff.docsImpact;
            const impactedCount = impact.impactedFiles?.length || 0;
            const missingCount = impact.missingDocs?.length || 0;
            
            if (impactedCount > 0 || missingCount > 0) {
              body += `\n## ðŸ“š Documentation Impact\n\n`;
              
              if (impactedCount > 0) {
                body += `### Files Needing Updates\n\n`;
                body += `| File | Issues |\n|------|--------|\n`;
                for (const file of impact.impactedFiles.slice(0, 10)) {
                  body += `| \`${file.file}\` | ${file.references.length} reference(s) |\n`;
                }
                if (impactedCount > 10) {
                  body += `\n_...and ${impactedCount - 10} more file(s)_\n`;
                }
              }
              
              if (missingCount > 0) {
                body += `\n### Missing Documentation\n\n`;
                for (const name of impact.missingDocs.slice(0, 5)) {
                  body += `- \`${name}()\` - new export with no docs\n`;
                }
                if (missingCount > 5) {
                  body += `\n_...and ${missingCount - 5} more_\n`;
                }
              }
              
              // Expandable details
              if (impactedCount > 0) {
                body += `\n<details>\n<summary>View details</summary>\n\n`;
                for (const file of impact.impactedFiles.slice(0, 5)) {
                  body += `#### ${file.file}\n\n`;
                  for (const ref of file.references.slice(0, 5)) {
                    const label = ref.changeType === 'signature-changed' ? 'signature changed' :
                                  ref.changeType === 'removed' ? 'removed' : 'deprecated';
                    body += `- **Line ${ref.line}**: \`${ref.exportName}\` (${label})\n`;
                  }
                  if (file.references.length > 5) {
                    body += `- _...and ${file.references.length - 5} more_\n`;
                  }
                  body += `\n`;
                }
                body += `</details>\n`;
              }
            }
          }
          
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const existing = comments.find(c => c.body?.includes('DocCov Report'));
          
          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }
      env:
        DIFF_RESULT: ${{ steps.diff.outputs.result }}

