import type { ReportStats } from './stats';

function bar(pct: number, width = 10): string {
  const filled = Math.round((pct / 100) * width);
  return '█'.repeat(filled) + '░'.repeat(width - filled);
}

export function renderMarkdown(stats: ReportStats, options: { limit?: number } = {}): string {
  const limit = options.limit ?? 20;
  const lines: string[] = [];

  lines.push(`# DocCov Report: ${stats.packageName}@${stats.version}`);
  lines.push('');
  lines.push(`**Coverage: ${stats.coverageScore}%** \`${bar(stats.coverageScore)}\``);
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Exports | ${stats.totalExports} |`);
  lines.push(`| Fully documented | ${stats.fullyDocumented} |`);
  lines.push(`| Partially documented | ${stats.partiallyDocumented} |`);
  lines.push(`| Undocumented | ${stats.undocumented} |`);
  lines.push(`| Drift issues | ${stats.driftCount} |`);

  // Signal coverage
  lines.push('');
  lines.push('## Coverage by Signal');
  lines.push('');
  lines.push('| Signal | Coverage |');
  lines.push('|--------|----------|');
  for (const [sig, s] of Object.entries(stats.signalCoverage)) {
    lines.push(`| ${sig} | ${s.pct}% \`${bar(s.pct, 8)}\` |`);
  }

  // By kind
  if (stats.byKind.length > 0) {
    lines.push('');
    lines.push('## Coverage by Kind');
    lines.push('');
    lines.push('| Kind | Count | Avg Score |');
    lines.push('|------|-------|-----------|');
    for (const k of stats.byKind) {
      lines.push(`| ${k.kind} | ${k.count} | ${k.avgScore}% |`);
    }
  }

  // Lowest coverage exports
  const lowExports = stats.exports.filter((e) => e.score < 100).slice(0, limit);
  if (lowExports.length > 0) {
    lines.push('');
    lines.push('## Lowest Coverage Exports');
    lines.push('');
    lines.push('| Export | Kind | Score | Missing |');
    lines.push('|--------|------|-------|---------|');
    for (const e of lowExports) {
      lines.push(`| \`${e.name}\` | ${e.kind} | ${e.score}% | ${e.missing.join(', ') || '-'} |`);
    }
    const totalLow = stats.exports.filter((e) => e.score < 100).length;
    if (totalLow > limit) {
      lines.push(`| ... | | | ${totalLow - limit} more |`);
    }
  }

  // Drift issues
  if (stats.driftIssues.length > 0) {
    lines.push('');
    lines.push('## Drift Issues');
    lines.push('');
    lines.push('| Export | Type | Issue |');
    lines.push('|--------|------|-------|');
    for (const d of stats.driftIssues.slice(0, limit)) {
      const hint = d.suggestion ? ` → ${d.suggestion}` : '';
      lines.push(`| \`${d.exportName}\` | ${d.type} | ${d.issue}${hint} |`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [DocCov](https://doccov.com)*');

  return lines.join('\n');
}
